version: "3"

services:
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
    links:
      - server

  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
    # environment:
    #   - CARGO_INCREMENTAL=1
    command: bash -c "cargo watch -x run"

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}
